# 初めてのJavaScript第3版 第14章
[全体目次へ戻る](index.md)

## 14章 非同期プログラミング
- 非同期的処理が必要な対象
  + ユーザからの入力
  + ネットワーク経由のリクエスト
  + ファイル入出力
  + 操作の遅延
- JavaScriptのアプリケーションはシングルスレッドで実行される

### Callback-Based
- 非同期処理を行う関数に、「処理が終わった後に呼び出す関数」を登録する
  + `setTimeOut(cb, timeOut)`/`setInterval(cb, interval)`: それぞれ、指定時間後/指定時間ごとに関数`cb`を呼び出す
  + `clearInterval(id)`: `setInterval`による繰り返しを止める。引数には`setInterval`呼び出し時に返る値(ID)を指定する

- Error-First Callback: コールバックの失敗を伝搬させるための手法。コールバックの第1引数をエラーオブジェクトにする

```js
const fs = require('fs');
const fname = 'notexist.txt';
// 第2引数のコールバックは、引数にエラーオブジェクトerrと読み込んだ内容dataをとる
fs.readFile(fname, (err, data) => {
  if(err) {
    return console.log(`file load error! ${fname}: ${err.message}`);
  }
  console.log(`contents:\n${data}`);
})
```

- コールバックベースでは、複数の非同期処理を逐次的につなげる際にネストが深くなるという問題がある(コールバック地獄)

### Promise-Based
- 非同期処理を`Promise`オブジェクトで包むことで、見通しの良い記述が可能となる
- 基本的な考え方
  + 非同期処理を行う関数を呼び出すと、`Promise`オブジェクトが返る
  + `Promise`は将来「成功」または「失敗」する非同期の計算を表現する
- プロミスの生成: 非同期処理を行う関数をコンストラクタ`new Promise()`に渡す
  + 処理関数は、それぞれ成功時と失敗時に呼び出す2つのコールバック関数を引数にとる
- プロミスの利用
  + `promise.then(onFulfilled[, onRejected])`: レシーバの`Promise`が成功した場合・失敗した場合それぞれの次の処理を記述する
    * `onRejected`は省略可
  + `promise.catch(onRejected)`: レシーバの`Promise`が失敗した場合の次の処理を記述する
- `then`に渡す処理で`Promise`を返してさらに`then`を続けることで、非同期処理の連鎖を記述できる


```js
function countdown(seconds) {
  // resolve: 成功時, reject: 失敗時のコールバック
  return new Promise((resolve, reject) => {
    for(let i = seconds; i >= 0; i--) {
      setTimeOut(() => {
        if(i > 0) console.log(i + "...");
        else resolve(console.log("GO!"));
      }, (seconds - i) * 1000);
    }
  });
}

const p = countdown(5);
p.then(
  // onFulfilled
  () => {
    console.log('成功');,
  },
  // onRejected
  (err) => {
    console.log('エラー: ${err.message}');
  }
);
```

- `Promise.all()`: `Promise`の配列をとり、全ての非同期処理を並列に実行する。全ての処理が成功したら全体として成功となり、1つでも失敗した場合はその時点で全体が失敗となる
  + 成功時の結果は配列で返る
- `Promise.race()`: 複数の非同期処理を並列に実行し、最も早く結果が確定した処理の結果を最終的な結果とする

### Generator-Based
- ジェネレータを利用することで、非同期処理をさらに簡潔に記述できる
- ジェネレータランナー: 「非同期処理を表現するジェネレータ」の処理を実行する関数

```js
// ジェネレータランナー
function grun(g) {
  const it = g();
  (function iterate(val) {
    const x = it.next(val);
    if(!x.done) {
      // 結果がPromiseなら、次の処理(iterate)を続ける
      if(x.value instanceof Promise) {
        x.value.then(iterate).catch(err => it.throw(err));
      }
      // 結果がPromise以外なら、得られた結果をそのまま返す
      else {
        // 同期的な再帰呼び出しを避ける
        setTimeOut(iterate, 0, x.value);
      }
    }
  })();
}

function readFile(filename) {
  return new Promise((resolve, reject) => {
    fs.readFile(filename, "utf-8", (err, data) => err ? reject(err) : resolve(data));
  });
}
function writeFile(filename, data) {
  return new Promise((resolve, reject) => {
    fs.writeFile(filename, data, err => err ? reject(err) : resolve("OK"));
  });
}
// 非同期処理の連鎖
function* fileReadAndWrite() {
  const dataA = yield readFile('a.txt');
  const dataB = yield readFile('b.txt');
  const dataC = yield readFile('c.txt');
  yield writeFile('d.txt', dataA + dataB + dataC);
}

// 利用
grun(fileReadAndWrite);
```

- 例外処理を行う場合は、ジェネレータ関数の中で同期的な処理と同様に`try-catch`を使えばよい
- ジェネレータランナーライブラリ
  + [co](https://github.com/tj/co)
  + [Koa(coと連携可能なWebフレームワーク)](http://koajs.com)
***

[前へ](c12.md) /
[全体目次へ戻る](index.md) /
[次へ](c18.md)
